package com.woniu.mapper;

import com.woniu.entity.Gl;
import com.woniu.entity.GlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int countByExample(GlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int deleteByExample(GlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int insert(Gl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int insertSelective(Gl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    List<Gl> selectByExample(GlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    Gl selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Gl record, @Param("example") GlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int updateByExample(@Param("record") Gl record, @Param("example") GlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int updateByPrimaryKeySelective(Gl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    int updateByPrimaryKey(Gl record);
}