server:
  port: 10001

spring:
  application:
    name: feigncustomer

user:
  userSericeURL: http://PROVIDER/

eureka:
  client:
    service-url:
      defaultZone:
        http://admin:ilovelaohan@localhost:9999/eureka/,http://admin:ilovelaohan@localhost:9998/eureka/,http://admin:ilovelaohan@localhost:9997/eureka/ #Eureka的服务器的地址
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
