package com.woniu.rediscache.entity;

import java.io.Serializable;

public class Car implements Serializable {
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "Car{" +
                "cid=" + cid +
                ", cname='" + cname + '\'' +
                ", pid=" + pid +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cid
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cname
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.pid
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cid
     *
     * @return the value of car.cid
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cid
     *
     * @param cid the value for car.cid
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cname
     *
     * @return the value of car.cname
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cname
     *
     * @param cname the value for car.cname
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.pid
     *
     * @return the value of car.pid
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.pid
     *
     * @param pid the value for car.pid
     *
     * @mbggenerated Fri Nov 15 09:45:21 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}