server: 
  port: 8000
  
spring: 
  application:
    name: customer  

eureka: 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone:
        http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true      