server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ybls
    username: root
    password: ilovelaohan

logging:
  level:
    com:
      woniu:
        debug