package com.woniu.entity;

import java.io.Serializable;

public class Gl implements Serializable{
    /**   
	 * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)   
	 */ 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl.lid
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    private Integer lid;

    @Override
	public String toString() {
		return "Gl [lid=" + lid + ", lname=" + lname + ", zm=" + zm + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl.lname
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl.zm
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    private String zm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl.lid
     *
     * @return the value of gl.lid
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl.lid
     *
     * @param lid the value for gl.lid
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl.lname
     *
     * @return the value of gl.lname
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl.lname
     *
     * @param lname the value for gl.lname
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    public void setLname(String lname) {
        this.lname = lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl.zm
     *
     * @return the value of gl.zm
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    public String getZm() {
        return zm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl.zm
     *
     * @param zm the value for gl.zm
     *
     * @mbggenerated Wed Aug 21 15:16:10 CST 2019
     */
    public void setZm(String zm) {
        this.zm = zm;
    }
}