package com.woniu.provider.entity;

public class Panda {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda.pid
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda.pname
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda.descr
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    private String descr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda.pid
     *
     * @return the value of panda.pid
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda.pid
     *
     * @param pid the value for panda.pid
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda.pname
     *
     * @return the value of panda.pname
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda.pname
     *
     * @param pname the value for panda.pname
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda.descr
     *
     * @return the value of panda.descr
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda.descr
     *
     * @param descr the value for panda.descr
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }
}