package com.woniu.provider.mapper;

import com.woniu.provider.entity.Panda;
import com.woniu.provider.entity.PandaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PandaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int countByExample(PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int deleteByExample(PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int insert(Panda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int insertSelective(Panda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    List<Panda> selectByExampleWithBLOBs(PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    List<Panda> selectByExample(PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    Panda selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Panda record, @Param("example") PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Panda record, @Param("example") PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int updateByExample(@Param("record") Panda record, @Param("example") PandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int updateByPrimaryKeySelective(Panda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Panda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda
     *
     * @mbggenerated Fri Nov 22 12:45:19 CST 2019
     */
    int updateByPrimaryKey(Panda record);
}