server: 
  port: 10000
  
spring: 
  application:
    name: zuul
    
#做转发

zuul: 
  routes:
    goods: 
      path: /goods/**   
      service-id: PROVIDER
    orders: 
      path: /orders/**   
      service-id: PROVIDER1
      
eureka: 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone:
        http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true        
      
    
