server:
  port: 10000

spring:
  application:
    name: customer

user:
  userSericeURL: http://PROVIDER/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true