server: 
  port: 9000
  
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ybls?characterEncoding=UTF-8
    username: root
    password: ilovelaohan
    
logging:
  level:
    com: 
      woniu: 
        mapper: debug     

#mybatis的配置文件在那里    
mybatis:
  config-location: classpath:mybatisConfig.xml   
      
  
